spring.application.name=java_pro_homework8

spring.datasource.url=jdbc:mysql://localhost:3306/exchange?serverTimezone=Europe/Kiev
spring.datasource.username=root
spring.datasource.password=Postoenko50!

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true

fixer.api.key=32e7de9474eed326c1bfab7ea945e955

logging.level.org.springframework.security=DEBUG